apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Loki Direct
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
      - name: Loki ACLs
        type: loki
        access: proxy
        url: http://loki-acls:3100
        isDefault: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-datasources
