apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loki
    spec:
      containers:
      - image: grafana/loki:2.1.0
        name: loki
        resources: {}
status: {}
