apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: loki-acls
  name: loki-acls
spec:
  ports:
  - name: 3100-3100
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki-acls
  type: ClusterIP
status:
  loadBalancer: {}
