apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: loki
  name: loki
spec:
  ports:
  - name: 3100-3100
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki
  type: ClusterIP
status:
  loadBalancer: {}
